export default {
  coops: [
    {
      name: "COTAGRO C.L",
      cuit: "30613203374",
      active: true,
      contract: "https://www.google.com",
      acct_type: "CONTABLE",
      provincia: "Buenos Aires",
      localidad: "General Cabrera",
      phone: "1122445522",
      email: "robertitto@cotagro.com",
      user: "",
      credit_amnt: 5000
    },
    {
      name: "ACA CDC",
      cuit: "30613203374",
      active: true,
      contract: "https://www.bing.com",
      acct_type: "CORRIENTE",
      provincia: "Santiago Del Estero",
      localidad: "Tio Pujio",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "",
      credit_amnt: 500000
    },
    {
      name: "COOPE VALIDACION",
      cuit: "30613203374",
      active: true,
      contract: "https://www.hotmail.com",
      acct_type: "CORRIENTE",
      provincia: "Buenos Aires",
      localidad: "Ciudadela",
      phone: "1122445522",
      email: "jgallego@al2.com.ar",
      user: "",
      credit_amnt: 12000
    },
    {
      name: "COOP AGROPEC DE AR.",
      cuit: "30613203374",
      active: false,
      contract: "https://www.yahoo.com",
      acct_type: "CONTABLE",
      provincia: "Córdoba",
      localidad: "Marcos Juarez",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "ACA CDC",
      credit_amnt: 0
    },
    {
      name: "COTAGRO C.L",
      cuit: "30613203374",
      active: true,
      contract: "https://www.google.com",
      acct_type: "CONTABLE",
      provincia: "Buenos Aires",
      localidad: "General Cabrera",
      phone: "1122445522",
      email: "robertitto@cotagro.com",
      user: "",
      credit_amnt: 5000
    },
    {
      name: "ACA CDC",
      cuit: "30613203374",
      active: true,
      contract: "https://www.bing.com",
      acct_type: "CORRIENTE",
      provincia: "Santiago Del Estero",
      localidad: "Tio Pujio",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "",
      credit_amnt: 500000
    },
    {
      name: "COOPE VALIDACION",
      cuit: "30613203374",
      active: true,
      contract: "https://www.hotmail.com",
      acct_type: "CORRIENTE",
      provincia: "Buenos Aires",
      localidad: "Ciudadela",
      phone: "1122445522",
      email: "jgallego@al2.com.ar",
      user: "",
      credit_amnt: 12000
    },
    {
      name: "COOP AGROPEC DE AR.",
      cuit: "30613203374",
      active: false,
      contract: "https://www.yahoo.com",
      acct_type: "CONTABLE",
      provincia: "Córdoba",
      localidad: "Marcos Juarez",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "ACA CDC",
      credit_amnt: 0
    },
    {
      name: "COTAGRO C.L",
      cuit: "30613203374",
      active: true,
      contract: "https://www.google.com",
      acct_type: "CONTABLE",
      provincia: "Buenos Aires",
      localidad: "General Cabrera",
      phone: "1122445522",
      email: "robertitto@cotagro.com",
      user: "",
      credit_amnt: 5000
    },
    {
      name: "ACA CDC",
      cuit: "30613203374",
      active: true,
      contract: "https://www.bing.com",
      acct_type: "CORRIENTE",
      provincia: "Santiago Del Estero",
      localidad: "Tio Pujio",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "",
      credit_amnt: 500000
    },
    {
      name: "COOPE VALIDACION",
      cuit: "30613203374",
      active: true,
      contract: "https://www.hotmail.com",
      acct_type: "CORRIENTE",
      provincia: "Buenos Aires",
      localidad: "Ciudadela",
      phone: "1122445522",
      email: "jgallego@al2.com.ar",
      user: "",
      credit_amnt: 12000
    },
    {
      name: "COOP AGROPEC DE AR.",
      cuit: "30613203374",
      active: false,
      contract: "https://www.yahoo.com",
      acct_type: "CONTABLE",
      provincia: "Córdoba",
      localidad: "Marcos Juarez",
      phone: "1122445522",
      email: "javalis@acacop.com",
      user: "ACA CDC",
      credit_amnt: 0
    }
  ],
  socios: [
    {
      name: "Gallego, Jorge",
      cooperativa: "COOPERATIVA_VALIDACIONES",
      cuit: "30613203374",
      estado: "Notificación pendiente",
      partner: "SI",
      credit_amnt: 0,
      checking_acct: 1122445522
    },
    {
      name: "López Díaz, Javier",
      cooperativa: "ACA CDC",
      cuit: "30613203374",
      estado: "Informado",
      partner: "NO",
      credit_amnt: 0,
      checking_acct: 1122445522
    },
    {
      name: "Pérez, Luciana",
      cooperativa: "COTAGRO C.L.",
      cuit: "30613203374",
      estado: "Inicial",
      partner: "SI",
      credit_amnt: 3000,
      checking_acct: 1122445522
    },
    {
      name: "González, Julián",
      cooperativa: "COTAGRO C.L.",
      cuit: "30613203374",
      estado: "Inicial",
      partner: "NO",
      credit_amnt: 25000,
      checking_acct: 1122445522
    }
  ],
  transactions: [
    {
      partner: "COTAGRO C.L.",
      debit_cuit: "30613203374",
      credit_cuit: "30613203374",
      id: "30613203374",
      date: "12/11/2020",
      amount: 2000,
      type: 1,
      detail: "jakshdkjahs",
      state: "kajshdkjashd"
    },
    {
      partner: "COTAGRO C.L.",
      debit_cuit: "30613203374",
      credit_cuit: "30613203374",
      id: "30613203374",
      date: "12/11/2020",
      amount: 2000,
      type: 1,
      detail: "jakshdkjahs",
      state: "kajshdkjashd"
    },
    {
      partner: "COTAGRO C.L.",
      debit_cuit: "30613203374",
      credit_cuit: "30613203374",
      id: "30613203374",
      date: "12/11/2020",
      amount: 2000,
      type: 1,
      detail: "jakshdkjahs",
      state: "kajshdkjashd"
    },
    {
      partner: "COTAGRO C.L.",
      debit_cuit: "30613203374",
      credit_cuit: "30613203374",
      id: "30613203374",
      date: "12/11/2020",
      amount: 2000,
      type: 1,
      detail: "jakshdkjahs",
      state: "kajshdkjashd"
    }
  ],
  users: [
    {
    username: 'ACACDC',
    fullname:'COOPE_VALID',
    cuit: '30613203374',
    cargo: 'Empleado',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    },
    {
    username: 'POZZI',
    fullname:'ACA CDC',
    cuit: '30613203374',
    cargo: 'Gerente',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    },
    {
    username: 'ACADCDCR',
    fullname:'COOPE_VALID',
    cuit: '30613203374',
    cargo: 'Empleado',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    },
    {
    username: 'ACADFCdfDC',
    fullname:'COOPE_VALID',
    cuit: '30613203374',
    cargo: 'Empleado',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    },
    {
    username: 'DFACACDC3',
    fullname:'COOPE_VALID',
    cuit: '30613203374',
    cargo: 'Empleado',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    },
    {
    username: '2ACACDC',
    fullname:'COOPE_VALID',
    cuit: '30613203374',
    cargo: 'Empleado',
    cooperativa: 'ACA CDC',
    estado: 'Procesado',
    password: 'lkjdfdlfjf',
    }
  ]
}
